[workspace]
resolver = "3"
members = [
  "allergies",
  "binary-search",
  "bottle-song",
  "dot-dsl",
  "fizzy",
  "gigasecond",
  "grade-school",
  "react",
  "reverse-string",
  "robot-name",
  "simple-linked-list",
  "space-age",
  "todo",
]
